name: Auto Bump Bot

on:
  schedule:
    # Runs at minute 0 past every 2nd hour (0, 2, 4, 6... UTC)
    - cron: '0 */2 * * *'
  # Allows you to click a button to test it manually
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Libraries
      run: npm install

    - name: Run Bumper Script
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
      run: node index.js
