name: Auto Bump Bot

on:
  schedule:
    # 2 Hours and 10 Minutes Interval Schedule
    # Run 1 & 7:  00:00, 13:00
    - cron: '0 0,13 * * *'
    # Run 2 & 8:  02:10, 15:10
    - cron: '10 2,15 * * *'
    # Run 3 & 9:  04:20, 17:20
    - cron: '20 4,17 * * *'
    # Run 4 & 10: 06:30, 19:30
    - cron: '30 6,19 * * *'
    # Run 5 & 11: 08:40, 21:40
    - cron: '40 8,21 * * *'
    # Run 6 & 12: 10:50, 23:50
    - cron: '50 10,23 * * *'
    
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Libraries
      run: npm install

    - name: Run Bumper Script
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
      run: node index.js
